[app]
name = "keyauth"
key  = "this is your app key"

[app.http]
host = "127.0.0.1"
port = "8050"

[app.grpc]
host = "127.0.0.1"
port = "18050"


[mongodb]
endpoints = ["192.168.0.101:27017"]
username = "keyauth"
password = "123456"
database = "keyauth"

[redis]
address = "192.168.0.101"
password = "123456"
db = 0
port = "6379"

[mcenter]
address = "127.0.0.1:18010"
client_id = "JQ18r7kDkPK8p0OhiL5oUYUd"
client_secret = "01p3iXhorrSIEYhcIOXeWve6NbBuPoCk"

[log]
level = "debug"
path = "logs"
format = "text"
to = "stdout"
